import React, { useState, useEffect } from 'react';
import {
  Box,
  Typography,
  Paper,
  Button,
  TextField,
  Grid,
  Card,
  CardContent,
  CardActionArea,
  Chip,
  Alert,
  CircularProgress,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  List,
  ListItem,
  ListItemText,
  ListItemIcon
} from '@mui/material';
import {
  Description as DocumentIcon,
  Download as DownloadIcon,
  Add as AddIcon,
  CheckCircle as CheckIcon
} from '@mui/icons-material';

const PDFGenerator = () => {
  const [templates, setTemplates] = useState([]);
  const [selectedTemplate, setSelectedTemplate] = useState(null);
  const [formData, setFormData] = useState({});
  const [generating, setGenerating] = useState(false);
  const [generatedPDF, setGeneratedPDF] = useState(null);
  const [showPreview, setShowPreview] = useState(false);
  const [error, setError] = useState(null);

  const loadTemplates = async () => {
    try {
      const response = await fetch('http://localhost:3001/api/generator/templates');
      const data = await response.json();
      
      console.log('Templates response:', data); // Debug log
      
      if (data.success && data.templates) {
        setTemplates(data.templates);
        console.log('Templates loaded:', data.templates); // Debug log
      } else {
        setError('Failed to load document templates');
      }
    } catch (err) {
      setError('Failed to connect to document generator');
      console.error('Error loading templates:', err);
    }
  };

  // Load templates on component mount
  useEffect(() => {
    loadTemplates();
    
    // Fallback: Add mock templates after 3 seconds if none loaded
    const fallbackTimer = setTimeout(() => {
      if (templates.length === 0) {
        console.log('Adding fallback templates');
        setTemplates([
          {
            id: 'lease_agreement',
            name: 'Lease Agreement',
            description: 'Residential rental agreement template',
            fields: ['landlord_name', 'tenant_name', 'property_address', 'rent_amount', 'lease_term']
          },
          {
            id: 'service_contract',
            name: 'Service Contract',
            description: 'Professional service agreement template',
            fields: ['service_provider', 'client_name', 'service_description', 'payment_terms', 'duration']
          },
          {
            id: 'nda',
            name: 'Non-Disclosure Agreement',
            description: 'Confidentiality agreement template',
            fields: ['disclosing_party', 'receiving_party', 'confidential_info', 'duration', 'purpose']
          },
          {
            id: 'employment_contract',
            name: 'Employment Contract',
            description: 'Employee agreement template',
            fields: ['employer', 'employee_name', 'position', 'salary', 'start_date', 'benefits']
          }
        ]);
      }
    }, 3000);
    
    return () => clearTimeout(fallbackTimer);
  }, [templates.length]);

  const handleTemplateSelect = (template) => {
    setSelectedTemplate(template);
    setFormData({});
    setGeneratedPDF(null);
    setError(null);
  };

  const handleInputChange = (field, value) => {
    setFormData(prev => ({
      ...prev,
      [field]: value
    }));
  };

  const generatePDF = async () => {
    if (!selectedTemplate) return;

    setGenerating(true);
    setError(null);

    try {
      // For demo purposes, simulate PDF generation
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Create a mock PDF data (base64 encoded simple PDF)
      const mockPDFData = "JVBERi0xLjMKJcTl8uXrp/Og0MTGCjQgMCBvYmoKPDwKL0xlbmd0aCA0NDEKL0ZpbHRlciAvRmxhdGVEZWNvZGUKPj4Kc3RyZWFtCngBXZDBCsIwDIafJQeP7W+apD1K";
      
      setGeneratedPDF(mockPDFData);
      setShowPreview(true);
      
    } catch (err) {
      setError('Failed to generate document');
      console.error('Error generating PDF:', err);
    } finally {
      setGenerating(false);
    }
  };

  const downloadPDF = () => {
    if (generatedPDF && selectedTemplate) {
      // Create a simple text content for demo
      const content = `
${selectedTemplate.name}

Generated on: ${new Date().toLocaleDateString()}

Document Details:
${Object.entries(formData).map(([key, value]) => 
  `${key.replace('_', ' ').toUpperCase()}: ${value}`
).join('\n')}

This is a demo document generated by SmartProBono.
      `.trim();
      
      // Create a downloadable text file for demo purposes
      const blob = new Blob([content], { type: 'text/plain' });
      const link = document.createElement('a');
      link.href = URL.createObjectURL(blob);
      link.download = `${selectedTemplate.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(link.href);
    }
  };

  const renderTemplateSelection = () => (
    <Box>
      <Typography variant="h6" gutterBottom>
        Choose Document Template
      </Typography>
      <Typography variant="body2" color="text.secondary" paragraph>
        Select a template to get started with your legal document.
      </Typography>
      
      {templates.length === 0 ? (
        <Alert severity="info" sx={{ mb: 2 }}>
          Loading templates... ({templates.length} loaded)
        </Alert>
      ) : null}
      
      <Grid container spacing={2}>
        {templates.map((template) => (
          <Grid item xs={12} sm={6} md={4} key={template.id}>
            <Card 
              sx={{ 
                height: '100%',
                transition: 'transform 0.2s',
                '&:hover': {
                  transform: 'translateY(-4px)',
                  boxShadow: 4
                }
              }}
            >
              <CardActionArea onClick={() => handleTemplateSelect(template)}>
                <Box sx={{ bgcolor: 'primary.lighter', p: 2, display: 'flex', justifyContent: 'center' }}>
                  <DocumentIcon fontSize="large" color="primary" />
                </Box>
                <CardContent>
                  <Typography variant="h6" component="div" gutterBottom>
                    {template.name}
                  </Typography>
                  <Typography variant="body2" color="text.secondary" paragraph>
                    {template.description}
                  </Typography>
                  <Box sx={{ display: 'flex', flexWrap: 'wrap', gap: 0.5 }}>
                    {template.fields.slice(0, 3).map((field) => (
                      <Chip 
                        key={field} 
                        label={field.replace('_', ' ')} 
                        size="small" 
                        variant="outlined"
                      />
                    ))}
                    {template.fields.length > 3 && (
                      <Chip 
                        label={`+${template.fields.length - 3} more`} 
                        size="small" 
                        variant="outlined"
                        color="primary"
                      />
                    )}
                  </Box>
                </CardContent>
              </CardActionArea>
            </Card>
          </Grid>
        ))}
      </Grid>
    </Box>
  );

  const renderForm = () => {
    if (!selectedTemplate) return null;

    return (
      <Box>
        <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
          <DocumentIcon color="primary" sx={{ mr: 1 }} />
          <Typography variant="h6">
            {selectedTemplate.name}
          </Typography>
          <Button 
            variant="outlined" 
            size="small" 
            onClick={() => setSelectedTemplate(null)}
            sx={{ ml: 'auto' }}
          >
            Change Template
          </Button>
        </Box>

        <Typography variant="body2" color="text.secondary" paragraph>
          Fill in the details below to generate your document.
        </Typography>

        <Grid container spacing={2}>
          {selectedTemplate.fields.map((field) => (
            <Grid item xs={12} sm={6} key={field}>
              <TextField
                fullWidth
                label={field.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase())}
                value={formData[field] || ''}
                onChange={(e) => handleInputChange(field, e.target.value)}
                variant="outlined"
                size="small"
              />
            </Grid>
          ))}
        </Grid>

        <Box sx={{ mt: 3, display: 'flex', gap: 2 }}>
          <Button
            variant="contained"
            onClick={generatePDF}
            disabled={generating}
            startIcon={generating ? <CircularProgress size={20} /> : <AddIcon />}
          >
            {generating ? 'Generating...' : 'Generate Document'}
          </Button>
        </Box>
      </Box>
    );
  };

  const renderPreview = () => (
    <Dialog 
      open={showPreview} 
      onClose={() => setShowPreview(false)}
      maxWidth="md"
      fullWidth
    >
      <DialogTitle>
        <Box sx={{ display: 'flex', alignItems: 'center' }}>
          <CheckIcon color="success" sx={{ mr: 1 }} />
          Document Generated Successfully!
        </Box>
      </DialogTitle>
      <DialogContent>
        <Alert severity="success" sx={{ mb: 2 }}>
          Your {selectedTemplate?.name} has been generated and is ready for download.
        </Alert>
        
        <Typography variant="body2" color="text.secondary" paragraph>
          <strong>What's next:</strong>
        </Typography>
        <List dense>
          <ListItem>
            <ListItemIcon>
              <CheckIcon color="success" fontSize="small" />
            </ListItemIcon>
            <ListItemText primary="Review the document for accuracy" />
          </ListItem>
          <ListItem>
            <ListItemIcon>
              <CheckIcon color="success" fontSize="small" />
            </ListItemIcon>
            <ListItemText primary="Download and save a copy" />
          </ListItem>
          <ListItem>
            <ListItemIcon>
              <CheckIcon color="success" fontSize="small" />
            </ListItemIcon>
            <ListItemText primary="Share with the other party for review" />
          </ListItem>
          <ListItem>
            <ListItemIcon>
              <CheckIcon color="success" fontSize="small" />
            </ListItemIcon>
            <ListItemText primary="Consider having it reviewed by an attorney if needed" />
          </ListItem>
        </List>
      </DialogContent>
      <DialogActions>
        <Button onClick={() => setShowPreview(false)}>
          Close
        </Button>
        <Button 
          variant="contained" 
          onClick={downloadPDF}
          startIcon={<DownloadIcon />}
        >
          Download PDF
        </Button>
      </DialogActions>
    </Dialog>
  );

  return (
    <Box>
      <Paper sx={{ p: 3, mb: 3 }}>
        <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
          <DocumentIcon color="primary" sx={{ mr: 1, fontSize: 32 }} />
          <Typography variant="h5">
            PDF Generator
          </Typography>
        </Box>
        
        <Typography variant="body1" paragraph>
          Create professional legal documents in minutes! Choose a template, fill in your details, and generate a ready-to-use PDF.
        </Typography>
      </Paper>

      {error && (
        <Alert severity="error" sx={{ mb: 3 }}>
          {error}
        </Alert>
      )}

      {!selectedTemplate ? renderTemplateSelection() : renderForm()}
      {renderPreview()}
    </Box>
  );
};

export default PDFGenerator;
