#!/usr/bin/env python3

"""
Creates a sample PDF file for testing document uploads
"""

try:
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import letter
except ImportError:
    print("Installing required packages...")
    import subprocess
    import sys
    subprocess.check_call([sys.executable, "-m", "pip", "install", "reportlab"])
    from reportlab.pdfgen import canvas
    from reportlab.lib.pagesizes import letter

import os
from datetime import datetime

def create_sample_pdf(filename="sample_document.pdf"):
    """
    Create a sample PDF file with text and basic formatting
    """
    # Create a canvas to draw on
    c = canvas.Canvas(filename, pagesize=letter)
    width, height = letter
    
    # Title
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(width/2, height - 50, "Sample Legal Document")
    
    # Subtitle with date
    c.setFont("Helvetica", 14)
    c.drawCentredString(width/2, height - 80, f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    
    # Add a horizontal line
    c.line(50, height - 100, width - 50, height - 100)
    
    # Content
    c.setFont("Helvetica", 12)
    
    # Sample legal text
    legal_text = [
        "AGREEMENT AND TERMS OF SERVICE",
        "",
        "This document is a sample legal document created for testing purposes.",
        "It does not constitute actual legal advice or create any binding agreement.",
        "",
        "1. INTRODUCTION",
        "   This sample document demonstrates PDF generation capabilities.",
        "   Any resemblance to actual legal documents is coincidental.",
        "",
        "2. TERMS AND CONDITIONS",
        "   a) This is a test document only.",
        "   b) No rights or obligations arise from this document.",
        "   c) This document may be freely used for testing purposes.",
        "",
        "3. PRIVACY POLICY",
        "   This document does not collect or store any personal information.",
        "",
        "4. DISCLAIMER",
        "   THIS DOCUMENT IS PROVIDED 'AS IS' WITHOUT WARRANTY OF ANY KIND.",
        "",
        "5. CONTACT INFORMATION",
        "   For questions about this sample document, please contact:",
        "   email: info@smartprobono.org",
        "",
        "SIGNATURES:",
        "",
        "____________________________        ____________________________",
        "Party A                             Party B",
        "",
        "Date: ___________________           Date: ___________________"
    ]
    
    y_position = height - 150
    line_height = 15
    
    for line in legal_text:
        if not line:  # Empty line
            y_position -= line_height
            continue
            
        if line.startswith("SIGNATURES:"):
            y_position -= line_height * 2
            c.setFont("Helvetica-Bold", 12)
        elif line.startswith(("1.", "2.", "3.", "4.", "5.")):
            c.setFont("Helvetica-Bold", 12)
        else:
            c.setFont("Helvetica", 12)
            
        c.drawString(50, y_position, line)
        y_position -= line_height
    
    # Add a footer
    c.setFont("Helvetica", 8)
    c.drawString(50, 30, f"Generated by SmartProBono - Page 1 of 1")
    c.drawRightString(width - 50, 30, f"Sample ID: SP-{datetime.now().strftime('%Y%m%d-%H%M%S')}")
    
    # Save the PDF
    c.save()
    
    file_path = os.path.abspath(filename)
    file_size = os.path.getsize(filename)
    
    print(f"Sample PDF created at: {file_path}")
    print(f"File size: {file_size} bytes")
    
    return file_path

if __name__ == "__main__":
    create_sample_pdf() 