#!/bin/bash

echo "🚀 Quick Gemini Setup"
echo "===================="
echo ""
echo "Get your FREE Gemini API key (takes 2 minutes):"
echo ""
echo "1. Visit: https://makersuite.google.com/app/apikey"
echo "2. Click 'Get API Key'"
echo "3. Click 'Create API key in new project'"
echo "4. Copy the key (starts with AIzaSy...)"
echo ""
echo "Then add it to your .env file:"
echo ""
echo "GEMINI_API_KEY=your_key_here"
echo ""
echo "Benefits:"
echo "  ✅ 1,500 FREE requests per day"
echo "  ✅ Faster responses for complex queries"
echo "  ✅ Better quality for legal research"
echo "  ✅ No credit card required"
echo ""
echo "After adding the key, restart your server:"
echo "  cd backend && python combined_server.py"
