[build]
  base = "frontend"
  publish = "build"
  command = "npm cache clean --force && npm install --legacy-peer-deps && npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 