services:
  - type: web
    name: smartprobono-standalone
    env: python
    plan: free
    buildCommand: pip install -r requirements_standalone.txt
    startCommand: python3 app_standalone.py
    envVars:
      - key: PORT
        value: 8081
      - key: FLASK_ENV
        value: production
      - key: SUPABASE_URL
        value: https://ewtcvsohdgkthuyajyyk.supabase.co
      - key: SUPABASE_SERVICE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV3dGN2c29oZGdrdGh1eWFqeXlrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1NjQxMDQ2NCwiZXhwIjoyMDcxOTg2NDY0fQ._9KbvHJ6JohciGAqwHlQGerGr2xkHEr36OmSB5oQjng