services:
  - type: web
    name: pro-bono-backend
    env: python
    buildCommand: |
      apt-get update && apt-get install -y wkhtmltopdf
      cd backend && pip install -r requirements.txt
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0 