services:
  - type: web
    name: smartProBonoAPI
    env: python
    buildCommand: cd backend && pip install -r requirements.txt && pip install pdfkit
    startCommand: cd backend && gunicorn app:app
    envVars:
      - key: PDF_ENABLED
        value: false
    buildpacks:
      - url: heroku/python
      - url: https://github.com/heroku-buildpacks/apt
    aptBuildpackConfig:
      packages:
        - wkhtmltopdf
        
  - type: web
    name: smartProBonoFrontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: smartProBonoAPI
          type: web
          property: url 