openapi: 3.0.0
info:
  title: SmartProBono API
  version: 1.0.0
  description: API documentation for SmartProBono immigration form management system

servers:
  - url: http://localhost:5000
    description: Development server

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    FormTemplate:
      type: object
      properties:
        _id:
          type: string
        title:
          type: string
        description:
          type: string
        schema:
          type: object
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    FormSubmission:
      type: object
      properties:
        _id:
          type: string
        template_id:
          type: string
        status:
          type: string
          enum: [draft, submitted, under_review, approved, rejected]
        data:
          type: object
        comments:
          type: array
          items:
            $ref: '#/components/schemas/Comment'
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Comment:
      type: object
      properties:
        _id:
          type: string
        content:
          type: string
        user_id:
          type: string
        created_at:
          type: string
          format: date-time

    Attachment:
      type: object
      properties:
        _id:
          type: string
        filename:
          type: string
        url:
          type: string
        created_at:
          type: string
          format: date-time

    Error:
      type: object
      properties:
        error:
          type: string
        message:
          type: string

paths:
  /api/immigration/forms/templates:
    get:
      summary: List all form templates
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of form templates
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FormTemplate'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    post:
      summary: Create a new form template
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                schema:
                  type: object
      responses:
        '201':
          description: Form template created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormTemplate'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/immigration/forms:
    post:
      summary: Submit a new form
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                template_id:
                  type: string
                data:
                  type: object
      responses:
        '201':
          description: Form submitted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormSubmission'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/immigration/forms/search:
    get:
      summary: Search form submissions
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          schema:
            type: integer
            default: 10
        - name: status
          in: query
          schema:
            type: string
        - name: template_id
          in: query
          schema:
            type: string
      responses:
        '200':
          description: List of form submissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  forms:
                    type: array
                    items:
                      $ref: '#/components/schemas/FormSubmission'
                  total:
                    type: integer
                  page:
                    type: integer
                  per_page:
                    type: integer
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/immigration/forms/{form_id}:
    get:
      summary: Get form submission details
      security:
        - bearerAuth: []
      parameters:
        - name: form_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Form submission details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormSubmission'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

    put:
      summary: Update form submission
      security:
        - bearerAuth: []
      parameters:
        - name: form_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                data:
                  type: object
                status:
                  type: string
      responses:
        '200':
          description: Form updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FormSubmission'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/immigration/forms/{form_id}/comments:
    post:
      summary: Add a comment to a form
      security:
        - bearerAuth: []
      parameters:
        - name: form_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
      responses:
        '201':
          description: Comment added successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/immigration/forms/{form_id}/attachments:
    post:
      summary: Upload an attachment
      security:
        - bearerAuth: []
      parameters:
        - name: form_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '201':
          description: Attachment uploaded successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Attachment'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'

components:
  responses:
    UnauthorizedError:
      description: Authentication information is missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

    NotFoundError:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error' 