name: Deploy SmartProBono

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Frontend and Backend
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          # Disable cache to prevent package-lock.json issues
          # cache: 'npm'
          # cache-dependency-path: 'frontend/package-lock.json'
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: 'backend/requirements.txt'
          
      - name: Install frontend dependencies
        run: |
          cd frontend
          # Remove package-lock.json to force clean install
          rm -f package-lock.json
          # Install with bypass flags
          npm install --legacy-peer-deps --no-package-lock --force
          
      - name: Build frontend
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        run: |
          cd frontend
          npm run build
          
      - name: Install backend dependencies
        run: |
          cd backend
          pip install -r requirements.txt
          
      - name: Setup Cloudinary
        run: |
          cd backend
          python scripts/setup_cloudinary.py --test-only
          
      - name: Run database migrations
        run: |
          cd backend
          python -m flask db upgrade
          
      - name: Deploy to Netlify (Frontend)
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install -g netlify-cli
          cd frontend
          netlify deploy --prod --dir=build
          
      - name: Deploy to Render (Backend)
        if: success()
        env:
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"clearCache": "clear"}' 